name: CycloneDX GoMod Generate SBOM
author: Niklas Düster
description: Github action to generate a CycloneDX BOM for Go modules
inputs:
  version:
    description: The version of cyclonedx-gomod to use
    required: true
  output:
    description: Output path
    default: ./bom.xml
    required: false
  json:
    description: Output in JSON format
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'index.js'