name: CycloneDX GoMod Generate SBOM
author: Niklas Düster
description: Github action to generate a CycloneDX SBOM for Go modules
inputs:
  args:
    description: |
      Arguments to pass to cyclonedx-gomod.
      When not set, cyclonedx-gomod will only be downloaded, but not executed.
    required: false
  version:
    description: |
      The version of cyclonedx-gomod to use. 
      Can be a version range, in which case the latest version matching the range is chosen.
      Minimum allowed version is v1.0.0.
    required: true
runs:
  using: 'node12'
  main: 'index.js'
