on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run gh-gomod-generate-sbom Action
        uses: ./
        with:
          version: '0.8.1'
          